### ISSUE TITLE
Task 1

### ISSUE THREAD

**Issue by nadejdashed** [sninala/Native-JS-Assignemnt#1]
Very nce done:
- arrayElementsWithCommaDelimit
- basicMathematicalOperations. Only one comment. Please use space before break, remove space inside ( operation), add space between switch and (. So be very carefull with spaces. It increase or discrease readability
- oppositeNumber
- wordCount. However str == '' is extra check and better to wtire possitive sentance words ? words.length : 0;

Need improve:
- transporationOnVacation. You can calculate amount before calculation discount.
- calculatingWithFunctions. Nice that you try to tokenize, but it could be done easier. Need to rewrite tokenize and zero, one, ..... zero, one could be function that return from tokenize 
- getMiddleCharacter
1) extra check s.length == 1
2) middle_index could be calculated one time
3) middle_index2 is the next index after middle_index+1. Could be calculated easier
- partitionOn:
1) Don't have sence to responseFalse.concat(responseTrue);
2) You created 2 extra arrays. You can manipulate only initial array

**Comment by nadejdashed** [comment]
@sninala,
partitionOn - please try to look at this expresion one more time:
items.splice(false_idx++, 0, items.splice(i, 1)[0])

**Comment by sninala** [comment]
@nadejdashed , I have modified the code by splitting the logic into multiple lines. See if does makes sense now ..
