### ISSUE TITLE
set5

### ISSUE THREAD

**Issue by nadejdashed** [sninala/Native-JS-Assignemnt#2]
Nice work on 3-4 sets. Some corrections in set 5 should be added:
- extract-nested-object-reference.js currentObject is not necessary, you can use this

**Comment by sninala** [comment]
@nadejdashed , Please review the latest commit https://github.com/sninala/Native-JS-Assignemnt/commit/2e0cd7ecc6c8311e637f9a10cbcf8df4e1856421 and let me know if anymore changes needed..

**Comment by nadejdashed** [comment]
Thank you
